/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    'bike-categories': BikeCategory;
    'new-bikes': NewBike;
    'used-bikes': UsedBike;
    enquiries: Enquiry;
    'service-requests': ServiceRequest;
    orders: Order;
    pages: Page;
    'hero-slides': HeroSlide;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'bike-categories': BikeCategoriesSelect<false> | BikeCategoriesSelect<true>;
    'new-bikes': NewBikesSelect<false> | NewBikesSelect<true>;
    'used-bikes': UsedBikesSelect<false> | UsedBikesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'service-requests': ServiceRequestsSelect<false> | ServiceRequestsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'staff') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    syndication?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  /**
   * Uncheck to hide brand without deleting (e.g. discontinued lines).
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bike-categories".
 */
export interface BikeCategory {
  id: number;
  name: string;
  slug: string;
  group: 'road' | 'off-road' | 'atv' | 'other';
  image?: (number | null) | Media;
  description?: string | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "new-bikes".
 */
export interface NewBike {
  id: number;
  /**
   * e.g. "XSR900 GP"
   */
  displayName: string;
  slug: string;
  /**
   * Short marketing line, e.g. "Born Iconic"
   */
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Plain-text marketing description (auto-populated from manufacturer API). Paragraphs separated by blank lines.
   */
  descriptionText?: string | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  brand: number | Brand;
  category?: (number | null) | BikeCategory;
  year?: number | null;
  /**
   * Manufacturer model code (e.g. MTM890ASPT)
   */
  modelCode?: string | null;
  /**
   * Base model name without variant (e.g. XSR900)
   */
  baseModel?: string | null;
  /**
   * Recommended retail price (AUD, ex on-roads unless priceLabel says otherwise)
   */
  price?: number | null;
  /**
   * e.g. "Ride away" or "From"
   */
  priceLabel?: string | null;
  primaryImage?: (number | null) | Media;
  /**
   * External image URL (e.g. from Yamaha API). Used until image is downloaded into Media.
   */
  externalImageUrl?: string | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Available colours / colourways for this model.
   */
  colors?:
    | {
        name: string;
        /**
         * CSS hex code, e.g. #FFCC00
         */
        hex?: string | null;
        image?: (number | null) | Media;
        /**
         * External per-colour image URL (e.g. from Yamaha API). Used until image is downloaded into Media.
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  brochureUrl?: string | null;
  specs?: {
    engineType?: string | null;
    engineDisplacement?: string | null;
    bore?: string | null;
    compression?: string | null;
    lubrication?: string | null;
    fuelSystem?: string | null;
    ignition?: string | null;
    starter?: string | null;
    fuelTank?: string | null;
    oilCapacity?: string | null;
    finalDrive?: string | null;
    transmission?: string | null;
    frame?: string | null;
    frontSuspension?: string | null;
    rearSuspension?: string | null;
    frontBrakes?: string | null;
    rearBrakes?: string | null;
    frontTyre?: string | null;
    rearTyre?: string | null;
    length?: string | null;
    width?: string | null;
    height?: string | null;
    seatHeight?: string | null;
    wheelbase?: string | null;
    clearance?: string | null;
    weight?: string | null;
  };
  source: 'yamaha-api' | 'manual';
  /**
   * External provider ID (e.g. Yamaha API ID). Required for sync.
   */
  externalId?: string | null;
  /**
   * Last successful sync from external API.
   */
  lastSyncedAt?: string | null;
  /**
   * Raw payload from last sync. Used for re-sync and debugging.
   */
  rawApiData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'available' | 'pre-order' | 'discontinued' | 'hidden';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used-bikes".
 */
export interface UsedBike {
  id: number;
  /**
   * Internal dealer stock number.
   */
  stockNumber: string;
  /**
   * Customer-facing title, e.g. "2021 Yamaha MT-09 SP".
   */
  displayName: string;
  slug: string;
  /**
   * One-liner that runs above the description.
   */
  tagline?: string | null;
  /**
   * Marketing copy. Will be syndicated to bikesales.com.au.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * First photo is the cover. bikesales accepts up to 24 photos at 1024x768+.
   */
  photos?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  year: number;
  brand: number | Brand;
  /**
   * Base model, e.g. "MT-09".
   */
  model: string;
  /**
   * Variant / trim, e.g. "SP".
   */
  variant?: string | null;
  category?: (number | null) | BikeCategory;
  bodyType:
    | 'sport'
    | 'naked'
    | 'cruiser'
    | 'sport-touring'
    | 'touring'
    | 'adventure'
    | 'scooter'
    | 'enduro'
    | 'motocross'
    | 'dual-sport'
    | 'atv'
    | 'other';
  engineCc?: number | null;
  cylinders?: number | null;
  transmission?: ('manual' | 'automatic' | 'semi-auto' | 'cvt') | null;
  kms: number;
  condition: 'used' | 'demo';
  color?: string | null;
  /**
   * Internal — not published.
   */
  vin?: string | null;
  /**
   * Internal — not published.
   */
  engineNumber?: string | null;
  registrationStatus?: ('registered' | 'unregistered') | null;
  registrationState?: ('NSW' | 'VIC' | 'QLD' | 'WA' | 'SA' | 'TAS' | 'ACT' | 'NT') | null;
  registrationExpiryDate?: string | null;
  complianceDate?: string | null;
  buildDate?: string | null;
  price: number;
  /**
   * e.g. "Drive away" or "Plus on-road costs".
   */
  priceLabel?: string | null;
  /**
   * Customer-facing listing state. Separate from draft/published versioning.
   */
  listingStatus: 'draft' | 'available' | 'on-hold' | 'sold' | 'archived';
  soldDate?: string | null;
  syndication?: {
    bikesales?: {
      /**
       * Include this bike in the bikesales feed.
       */
      enabled?: boolean | null;
      /**
       * bikesales internal listing ID once syndicated.
       */
      externalId?: string | null;
      lastFeedAt?: string | null;
      lastError?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  type: 'new-bike' | 'used-bike' | 'finance' | 'parts' | 'general';
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  newBike?: (number | null) | NewBike;
  usedBike?: (number | null) | UsedBike;
  /**
   * Deposit amount available, in AUD. Optional.
   */
  financeDeposit?: number | null;
  /**
   * Customer-supplied trade-in details, if any.
   */
  financeTradeIn?: string | null;
  /**
   * Customer's preferred term, if specified.
   */
  financeTerm?: ('24' | '36' | '48' | '60' | '72') | null;
  /**
   * URL the form was submitted from.
   */
  pageUrl?: string | null;
  userAgent?: string | null;
  status?: ('new' | 'contacted' | 'in-progress' | 'closed-won' | 'closed-lost' | 'spam') | null;
  assignedTo?: (number | null) | User;
  /**
   * Internal notes — never shown to customer.
   */
  notes?:
    | {
        note: string;
        author?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests".
 */
export interface ServiceRequest {
  id: number;
  name: string;
  email: string;
  phone: string;
  bikeMake: string;
  bikeModel: string;
  bikeYear?: number | null;
  bikeKms?: number | null;
  bikeRego?: string | null;
  serviceType: 'scheduled' | 'repair' | 'tyres' | 'inspection' | 'warranty' | 'other';
  preferredDate?: string | null;
  description: string;
  status?: ('new' | 'confirmed' | 'in-workshop' | 'ready' | 'completed' | 'cancelled') | null;
  bookedDate?: string | null;
  estimatedCost?: number | null;
  actualCost?: number | null;
  workshopNotes?: string | null;
  /**
   * Auto-generated from name + bike.
   */
  displayTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Parts orders from yamahapartsaustralia.com.au. Customers paid via PayPal — fulfil via Evopos and update status as you go.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Generated server-side at checkout (e.g. YPA-12345).
   */
  orderNumber: string;
  status?: ('paid' | 'processing' | 'shipped' | 'picked-up' | 'completed' | 'cancelled' | 'refunded') | null;
  shippingMethod: 'au-flat' | 'pickup';
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  addressLine1?: string | null;
  addressLine2?: string | null;
  suburb?: string | null;
  state?: ('NSW' | 'VIC' | 'QLD' | 'WA' | 'SA' | 'TAS' | 'ACT' | 'NT') | null;
  postcode?: string | null;
  lineItems: {
    /**
     * EPC part number / Yamaha SKU.
     */
    sku: string;
    name: string;
    qty: number;
    /**
     * AUD, GST-inclusive (Yamaha RRP from EPC).
     */
    unitPrice: number;
    lineTotal: number;
    id?: string | null;
  }[];
  /**
   * AUD
   */
  subtotal: number;
  /**
   * AUD
   */
  shipping: number;
  /**
   * AUD
   */
  total: number;
  /**
   * sandbox or live at time of order.
   */
  paypalEnv?: string | null;
  paypalOrderId?: string | null;
  paypalCaptureId?: string | null;
  paypalCaptureStatus?: string | null;
  paypalPayerEmail?: string | null;
  /**
   * Internal — never shown to the customer. Tracking, packed-by, etc.
   */
  fulfilmentNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Homepage hero banners. Lower Order numbers appear first. Toggle Active off to hide a slide without deleting it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  /**
   * Internal label only — not shown to customers. e.g. "EOFY 2026 sale".
   */
  title: string;
  /**
   * Wide hero image, ideally 1920×600 or larger. The Media item's alt text becomes the slide's alt — set it well for accessibility and SEO.
   */
  image: number | Media;
  /**
   * Where the slide links when clicked. Leave blank to make the slide non-clickable. Internal links: /new-bikes?brand=yamaha. External: full https URL.
   */
  linkUrl?: string | null;
  /**
   * Lower numbers appear first. Default 100.
   */
  order?: number | null;
  /**
   * Uncheck to hide without deleting.
   */
  active?: boolean | null;
  /**
   * Optional. Slide hidden before this date.
   */
  startDate?: string | null;
  /**
   * Optional. Slide hidden after this date.
   */
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'bike-categories';
        value: number | BikeCategory;
      } | null)
    | ({
        relationTo: 'new-bikes';
        value: number | NewBike;
      } | null)
    | ({
        relationTo: 'used-bikes';
        value: number | UsedBike;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'service-requests';
        value: number | ServiceRequest;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        syndication?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  displayOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bike-categories_select".
 */
export interface BikeCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  group?: T;
  image?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "new-bikes_select".
 */
export interface NewBikesSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  descriptionText?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  brand?: T;
  category?: T;
  year?: T;
  modelCode?: T;
  baseModel?: T;
  price?: T;
  priceLabel?: T;
  primaryImage?: T;
  externalImageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  colors?:
    | T
    | {
        name?: T;
        hex?: T;
        image?: T;
        imageUrl?: T;
        id?: T;
      };
  brochureUrl?: T;
  specs?:
    | T
    | {
        engineType?: T;
        engineDisplacement?: T;
        bore?: T;
        compression?: T;
        lubrication?: T;
        fuelSystem?: T;
        ignition?: T;
        starter?: T;
        fuelTank?: T;
        oilCapacity?: T;
        finalDrive?: T;
        transmission?: T;
        frame?: T;
        frontSuspension?: T;
        rearSuspension?: T;
        frontBrakes?: T;
        rearBrakes?: T;
        frontTyre?: T;
        rearTyre?: T;
        length?: T;
        width?: T;
        height?: T;
        seatHeight?: T;
        wheelbase?: T;
        clearance?: T;
        weight?: T;
      };
  source?: T;
  externalId?: T;
  lastSyncedAt?: T;
  rawApiData?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used-bikes_select".
 */
export interface UsedBikesSelect<T extends boolean = true> {
  stockNumber?: T;
  displayName?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  year?: T;
  brand?: T;
  model?: T;
  variant?: T;
  category?: T;
  bodyType?: T;
  engineCc?: T;
  cylinders?: T;
  transmission?: T;
  kms?: T;
  condition?: T;
  color?: T;
  vin?: T;
  engineNumber?: T;
  registrationStatus?: T;
  registrationState?: T;
  registrationExpiryDate?: T;
  complianceDate?: T;
  buildDate?: T;
  price?: T;
  priceLabel?: T;
  listingStatus?: T;
  soldDate?: T;
  syndication?:
    | T
    | {
        bikesales?:
          | T
          | {
              enabled?: T;
              externalId?: T;
              lastFeedAt?: T;
              lastError?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  newBike?: T;
  usedBike?: T;
  financeDeposit?: T;
  financeTradeIn?: T;
  financeTerm?: T;
  pageUrl?: T;
  userAgent?: T;
  status?: T;
  assignedTo?: T;
  notes?:
    | T
    | {
        note?: T;
        author?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-requests_select".
 */
export interface ServiceRequestsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  bikeMake?: T;
  bikeModel?: T;
  bikeYear?: T;
  bikeKms?: T;
  bikeRego?: T;
  serviceType?: T;
  preferredDate?: T;
  description?: T;
  status?: T;
  bookedDate?: T;
  estimatedCost?: T;
  actualCost?: T;
  workshopNotes?: T;
  displayTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  shippingMethod?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  addressLine1?: T;
  addressLine2?: T;
  suburb?: T;
  state?: T;
  postcode?: T;
  lineItems?:
    | T
    | {
        sku?: T;
        name?: T;
        qty?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  total?: T;
  paypalEnv?: T;
  paypalOrderId?: T;
  paypalCaptureId?: T;
  paypalCaptureStatus?: T;
  paypalPayerEmail?: T;
  fulfilmentNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  linkUrl?: T;
  order?: T;
  active?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}